
all: tests

tests:
	../tkbinplay -r 44100 -b 16 -q -p 3 -o BUBBLES_44_16_Q_3.wav bubbles.ini
	../tkbinplay -r 44100 -b 16 -q -p 4 -o BUBBLES_44_16_Q_4.wav bubbles.ini
	../tkbinplay -r 44100 -b 16 -s -p 3 -o BUBBLES_44_16_S_3.wav bubbles.ini
	../tkbinplay -r 44100 -b 16 -s -p 4 -o BUBBLES_44_16_S_4.wav bubbles.ini
	../tkbinplay -r 48000 -b 16 -q -p 3 -o BUBBLES_48_16_Q_3.wav bubbles.ini
	../tkbinplay -r 48000 -b 16 -q -p 4 -o BUBBLES_48_16_Q_4.wav bubbles.ini
	../tkbinplay -r 48000 -b 16 -s -p 3 -o BUBBLES_48_16_S_3.wav bubbles.ini
	../tkbinplay -r 48000 -b 16 -s -p 4 -o BUBBLES_48_16_S_4.wav bubbles.ini

	../tkbinplay -r 44100 -b 16 -q -p 3 -o PITFALL2_44_16_Q_3.wav pitfall2.ini
	../tkbinplay -r 44100 -b 16 -q -p 4 -o PITFALL2_44_16_Q_4.wav pitfall2.ini
	../tkbinplay -r 44100 -b 16 -s -p 3 -o PITFALL2_44_16_S_3.wav pitfall2.ini
	../tkbinplay -r 44100 -b 16 -s -p 4 -o PITFALL2_44_16_S_4.wav pitfall2.ini
	../tkbinplay -r 48000 -b 16 -q -p 3 -o PITFALL2_48_16_Q_3.wav pitfall2.ini
	../tkbinplay -r 48000 -b 16 -q -p 4 -o PITFALL2_48_16_Q_4.wav pitfall2.ini
	../tkbinplay -r 48000 -b 16 -s -p 3 -o PITFALL2_48_16_S_3.wav pitfall2.ini
	../tkbinplay -r 48000 -b 16 -s -p 4 -o PITFALL2_48_16_S_4.wav pitfall2.ini

