
all: tests

tests:
	../tkbinplay -r 44100 -b 16 -w square -p 3 -o BUBBLES_44_16_Q_3.wav bubbles.ini
	../tkbinplay -r 44100 -b 16 -w square -p 4 -o BUBBLES_44_16_Q_4.wav bubbles.ini
	../tkbinplay -r 44100 -b 16 -w sine -p 3 -o BUBBLES_44_16_S_3.wav bubbles.ini
	../tkbinplay -r 44100 -b 16 -w sine -p 4 -o BUBBLES_44_16_S_4.wav bubbles.ini
	../tkbinplay -r 48000 -b 16 -w square -p 3 -o BUBBLES_48_16_Q_3.wav bubbles.ini
	../tkbinplay -r 48000 -b 16 -w square -p 4 -o BUBBLES_48_16_Q_4.wav bubbles.ini
	../tkbinplay -r 48000 -b 16 -w sine -p 3 -o BUBBLES_48_16_S_3.wav bubbles.ini
	../tkbinplay -r 48000 -b 16 -w sine -p 4 -o BUBBLES_48_16_S_4.wav bubbles.ini

	../tkbinplay -r 44100 -b 16 -w square -p 3 -o PITFALL2_44_16_Q_3.wav pitfall2.ini
	../tkbinplay -r 44100 -b 16 -w square -p 4 -o PITFALL2_44_16_Q_4.wav pitfall2.ini
	../tkbinplay -r 44100 -b 16 -w sine -p 3 -o PITFALL2_44_16_S_3.wav pitfall2.ini
	../tkbinplay -r 44100 -b 16 -w sine -p 4 -o PITFALL2_44_16_S_4.wav pitfall2.ini
	../tkbinplay -r 48000 -b 16 -w square -p 3 -o PITFALL2_48_16_Q_3.wav pitfall2.ini
	../tkbinplay -r 48000 -b 16 -w square -p 4 -o PITFALL2_48_16_Q_4.wav pitfall2.ini
	../tkbinplay -r 48000 -b 16 -w sine -p 3 -o PITFALL2_48_16_S_3.wav pitfall2.ini
	../tkbinplay -r 48000 -b 16 -w sine -p 4 -o PITFALL2_48_16_S_4.wav pitfall2.ini

	../tkbinplay -r 44100 -b 16 -w square -p 3 -o VIPER_44_16_Q_3.wav viper.ini
	../tkbinplay -r 44100 -b 16 -w square -p 4 -o VIPER_44_16_Q_4.wav viper.ini
	../tkbinplay -r 44100 -b 16 -w sine -p 3 -o VIPER_44_16_S_3.wav viper.ini
	../tkbinplay -r 44100 -b 16 -w sine -p 4 -o VIPER_44_16_S_4.wav viper.ini
	../tkbinplay -r 48000 -b 16 -w square -p 3 -o VIPER_48_16_Q_3.wav viper.ini
	../tkbinplay -r 48000 -b 16 -w square -p 4 -o VIPER_48_16_Q_4.wav viper.ini
	../tkbinplay -r 48000 -b 16 -w sine -p 3 -o VIPER_48_16_S_3.wav viper.ini
	../tkbinplay -r 48000 -b 16 -w sine -p 4 -o VIPER_48_16_S_4.wav viper.ini
